### ISSUE TITLE
插件用在开发状态时，无法正确使用

### ISSUE THREAD

**Issue by ZOUJIELynn** [sspku-yqLiu/DevUIHelper-LSP#1]
当下载ng-devui的源码下来时，插件会报错没有安装DevUI，需要考虑这种情况是否需要做开关

**Comment by sspku-yqLiu** [comment]
新版本添加了对devui文件夹的支持：
[demo]https://imgchr.com/i/Uel7FJ)
但是不支持在devui单独文件下的开发，例如：devui/button. 当您将button文件夹作为根文件夹的时候，他是不够支持的。

需要对单独的文件夹进行支持是比较困难的事情，因为这意味着在没有devui标记的文件夹下也必须提供插件支持，换句话说，任何项目的html文件都要受到支持，可能会带来一些不好的后果，例如某个组件库也使用了d-开头的tag标签，这会产生冲突。

如果非常需要的话，建议在某些地方添加devui标记 例如devui/devui-button 或 devui/d-button等。
当存在一些标记的时候 ，即使开发者的根目录不是devui，我们可以识别这些特征文件名并提供支持。

此外，现在的纠错提示功能主要是检测是否添加了必要的属性，这个检测是否安装了devui的提示如果实在不够好，我们就将在下个版本废弃掉。
